# Generated by Django 3.1.7 on 2021-05-11 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_membership'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
