# Generated by Django 3.1.7 on 2021-05-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210511_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='province',
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='code',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
