# Generated by Django 3.1.7 on 2021-05-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210511_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='code',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
