# Generated by Django 3.1.7 on 2021-05-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210511_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='membership',
            field=models.CharField(choices=[('no', 'NO'), ('1 years', '1 YEARS'), ('5 years', '5 YEARS')], default='No Membership', max_length=128),
        ),
    ]
