# Generated by Django 3.1.7 on 2021-05-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210511_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='price',
            field=models.CharField(choices=[('no', 'NO'), ('200', '1 YEARS'), ('1000', '5 YEARS')], default='No', max_length=128),
        ),
    ]
