# Generated by Django 3.1.7 on 2021-05-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_customer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='message',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
