# Generated by Django 3.1.8 on 2021-05-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_idea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='price',
            field=models.CharField(default='No', max_length=128),
        ),
    ]
